### PR TITLE
Build on macOS / Resume aborted build / Update gdb to latest

### PR DESCRIPTION
**Pull request by Windoze345**
- Updated gdb to version 8.3.0.
- Allow building on macOS (darwin)
- `--quiet-build` option, which will make the build quiet(er).
- `--resume` option, which will try to resume the last build.

### CODE REVIEW

**Comment by Windoze345** [comment]
Sorry about different changes in the same pull-request. I'm not that good with git branching yet...

**Comment by FreddieChopin** [comment]
Hello @Windoze345 ! Thanks for your contribution - a very valuable one! I was thinking about a way to resume the build a couple of times but my solutions were not good - I have a strong tendency to overcomplicate things. Your solution is simple and quite good (; Nice! I was also suspecting that MacOS build will fail for various reasons, but as I don't have a Mac, I had no way to actually test (and possibly fix) that. So I'm really grateful you solved both of these issues at once (;

> Sorry about different changes in the same pull-request. I'm not that good with git branching yet...

No worries about that - just a minor detail.

---

While it seems to work fine on my local PC, it doesn't work at all on travis-ci. The integration test would fail due to a timeout anyway, but it actually doesn't even start at all because of:

`./build-bleeding-edge-toolchain.sh: 76: ./build-bleeding-edge-toolchain.sh: OSTYPE: parameter not set`

On my system (Arch Linux) `$OSTYPE` is set to `linux-gnu`, I assume that on MacOS it is also set, but it seems that it is not an universally available variable and there are systems where it is just not set at all (like Ubuntu LTS on travis-ci). Maybe we should use some of these methods https://www.tldp.org/LDP/abs/html/parameter-substitution.html ? The `${parameter-default}` syntax is already used for `$XZ_OPT`, so it may be an option here. Or just test whether this variable is set somewhere at the beginning and if it is not. then define it to an empty string?

Let me know what do you think!

One more question - does building a version for Windows on Mac work fine? Did you test it?

**Comment by Windoze345** [comment]
Hello @FreddieChopin
Glad you like my changes :)

I changed it to call uname for os detection. $OSTYPE seems to be dependent on the used shell.
Travis CI starts building now...

Just FYI: I built without documentation on mac because I didn't feel like installing tex for that.
I also don't have MinGW installed so the Windows build might still not work on macOS

**Comment by FreddieChopin** [comment]
Hello @Windoze345 !

I tried to exercise the new resume feature and I managed to break it... I interrupted the build a couple of times (`Ctrl` + `C`) and finally it errored-out with a following (very helpful (; ) message:

```
make[8]: Leaving directory '/home/freddie/bleeding-edge-toolchain/buildNative/newlib-3.1.0/arm-none-eabi/thumb/v7+fp/hard/newlib/libm/complex'
Making all in machine
make[8]: Entering directory '/home/freddie/bleeding-edge-toolchain/buildNative/newlib-3.1.0/arm-none-eabi/thumb/v7+fp/hard/newlib/libm/machine'
make[8]: *** No rule to make target 'all'.  Stop.
make[8]: Leaving directory '/home/freddie/bleeding-edge-toolchain/buildNative/newlib-3.1.0/arm-none-eabi/thumb/v7+fp/hard/newlib/libm/machine'
make[7]: *** [Makefile:549: all-recursive] Error 1
make[7]: Leaving directory '/home/freddie/bleeding-edge-toolchain/buildNative/newlib-3.1.0/arm-none-eabi/thumb/v7+fp/hard/newlib/libm'
make[6]: *** [Makefile:641: all-recursive] Error 1
make[6]: Leaving directory '/home/freddie/bleeding-edge-toolchain/buildNative/newlib-3.1.0/arm-none-eabi/thumb/v7+fp/hard/newlib'
make[5]: *** [Makefile:452: all] Error 2
make[5]: Leaving directory '/home/freddie/bleeding-edge-toolchain/buildNative/newlib-3.1.0/arm-none-eabi/thumb/v7+fp/hard/newlib'
make[4]: *** [Makefile:1260: multi-do] Error 1
make[4]: Leaving directory '/home/freddie/bleeding-edge-toolchain/buildNative/newlib-3.1.0/arm-none-eabi/newlib'
make[3]: *** [Makefile:1176: all-multi] Error 2
make[3]: Leaving directory '/home/freddie/bleeding-edge-toolchain/buildNative/newlib-3.1.0/arm-none-eabi/newlib'
make[2]: *** [Makefile:452: all] Error 2
make[2]: Leaving directory '/home/freddie/bleeding-edge-toolchain/buildNative/newlib-3.1.0/arm-none-eabi/newlib'
make[1]: *** [Makefile:8492: all-target-newlib] Error 2
make[1]: Leaving directory '/home/freddie/bleeding-edge-toolchain/buildNative/newlib-3.1.0'
make: *** [Makefile:879: all] Error 2
```

I have absolutely no idea what is the problem here, however I have some suspicions. I think the problem may be due to the restart of a step that was partially completed, but with no prior clean-up. This may be especially visible with components like newlib, where "configure" step does NOT perform full configuration - some of it is done during "make" step...

What I would suggest would be - unfortunately - a small reduction of resume functionality. Maybe it would be better to NOT allow resuming of "make" after previous "configure". This way a clean-up would be possible - for each step that is resumed it would be possible to just delete the build folder completely. So you would be able to resume "newlib" build entirely (with a clean folder), but not in the middle (so it would not be possible to resume just "make" of "newlib", when previously "newlib's" "configure" step was completed and "make" was interrupted somewhere). I don't think it would be a big problem - "configure" steps are not that long, so I suppose that there won't be a big difference.

**Comment by Windoze345** [comment]
Hello @FreddieChopin

I also tried Ctrl+C and then resuming. I guess I always did it at the right time and didn't get any errors. :)

I only skipped the configure step to allow the build to continue, not because of the runtime.
But I agree that a always working build is more important than saving the last seconds.

I think the best solution would be to keep both tag-files (_configured & _built) but when the _configured file exists we delete the build-folder and start again at configuring.

Should I do that on all components or only on newlib (since newlib is the one with the complicated build system)?

**Comment by FreddieChopin** [comment]
> I think the best solution would be to keep both tag-files (_configured & _built) but when the _configured file exists we delete the build-folder and start again at configuring.

But in that case what is the purpose of having both files? I would propose to always start the interrupted step from scratch. So delete it no matter if it was interrupted during configure or build.

> Should I do that on all components or only on newlib (since newlib is the one with the complicated build system)?

I would prefer to do that for all components - the build process is so complex, that it is not possible to really test it, so it's better to be safe than sorry. Would you be able to improve your pull request like that?

Sorry for being so picky, the subject of your pull request (the main one - restarts) is a very complex one (at least in my opinion), so a few rounds of fixes/improvements is expected.

> But I agree that a always working build is more important than saving the last seconds.

Same here. The reason I did not implement any form of restart is that in reality you face all the possible problems only once. After you have all the components ready, then the script just works each time (excluding cases like unexpected system restarts or power interruptions <: ). I guess that a huge contributing factor was that I already experienced these initial problems long time ago, so they just don't affect me now. But they probably affect a huge majority of first-time users, so the addition is really valuable!

**Comment by Windoze345** [comment]
Hello @FreddieChopin

I updated my pull-request with the changes as you suggested!

**Comment by FreddieChopin** [comment]
I'm still here, but recently I'm very busy, so can't check the newest patch right now - sorry... Will get back here as soon as possible!

**Comment by FreddieChopin** [comment]
Sorry that it took so long, but recently I just don't know which top-priority thing I should do first...

Anyway - the whole thing is merged now, so thanks again for your time and efforts!

There are a couple of things worth improving, let me know whether you would like to (and could) work on them or maybe I should do them myself:

1. If you build a win32 and/or win64 version too and cancel somewhere during windows cross-builds, then the first step of windows build fails with:
```
********** Package
  100 %     206,0 MiB / 2 103,3 MiB = 0,098   2,4 MiB/s      14:23             
cp: cannot create regular file 'installWin32/share/gcc-9.1.0/python/libstdcxx/__init__.py': Permission denied
cp: cannot create regular file 'installWin32/share/gcc-9.1.0/python/libstdcxx/v6/printers.py': Permission denied
cp: cannot create regular file 'installWin32/share/gcc-9.1.0/python/libstdcxx/v6/xmethods.py': Permission denied
cp: cannot create regular file 'installWin32/share/gcc-9.1.0/python/libstdcxx/v6/__init__.py': Permission denied
```
Most likely because the files are read-only. However a tag-file to avoid the copies would be a good idea here.

2. When doing the same as above, the resume operation still does the packaging step, which takes quite a lot of time. I guess another tag-file for the package would be a good option.

3. Maybe rename `--quiet-build` to just `--quiet`? This commit - https://github.com/42Bastian/bleeding-edge-toolchain/commit/1c32ee6eee739d68f11c3e28e401b2757dc9d1ab - seems to suggest that adding `-s` to all `make` invocations would make the whole process even more silent. Maybe. Unless this is basically the same thing that your change does?

**Comment by Windoze345** [comment]
No worries! I don't have that much time for this either lately...

I've looked into the quiet build and did a separate pull request (#20)
But I'd prefer if you could look into the other things yourself. I don't have a MinGW environment installed here and can't test it...

**Comment by Trass3r** [comment]
>     1. If you build a win32 and/or win64 version too and cancel somewhere during windows cross-builds, then the first step of windows build fails with:
> cp: cannot create regular file 'installWin32/share/gcc-9.1.0/python/libstdcxx/__init__.py': Permission denied
> ```
> 
> Most likely because the files are read-only.

The same is true for copyNanoLibraries.

> 
>     1. When doing the same as above, the resume operation still does the packaging step, which takes quite a lot of time. I guess another tag-file for the package would be a good option.

I've been using a cmdline option: https://github.com/Trass3r/bleeding-edge-toolchain/commit/1c08a34c351fec1855e6768ccea69a58acb168f2

**Pull request merged**
