### PR TITLE
remove duplicate lines and fix brackets in gcc-6.3.0/gcc/config/arm/t--baremetal

### PR DESCRIPTION
**Pull request by dobryj**
second try to fix gcc-6.3.0/gcc/config/arm/t--baremetal

### CODE REVIEW

**Comment by dobryj** [comment]
Fail of test isn't surprise. Bug in the bracketing cause, that many multilibs was not compiled previously. 
It was all lines in section
ifneq (,$(filter armv7 armv7-r armv7-a,$(with_multilib_list)))
This build was failed due to time out, because need more time.

**Comment by dobryj** [comment]
Opps. I accidentaly revert your latest commit. I will create better version.

**Comment by FreddieChopin** [comment]
Don't worry about the timeouts in travis-ci - that is an issue we cannot solve right now. If the build times-out, then the most important thing is checked anyway - it builds fine (;

**Comment by FreddieChopin** [comment]
BTW - your "fix_t-baremetal-try3" branch looks OK.

**Pull request closed without merging**
