### PR TITLE
To upstream

### PR DESCRIPTION
**Pull request by nolange**
Some random improvements  suitable for upstream

### CODE REVIEW

**Comment by FreddieChopin** [comment]
Thanks!

**Comment by FreddieChopin** [comment]
@nolange 

How is this supposed to work:
```
		path=$(${triplet}-gcc -print-file-name=$dll)
		[ ! -e "${path}" ] || install -D -m644 "${path}" "${installFolder}/bin/${path##*/}"
```

In here it does not work for DLLs at all:

```
$ i686-w64-mingw32-gcc -print-file-name=libgcc_s_dw2-1.dll
libgcc_s_dw2-1.dll
```
Obviously `libgcc_s_dw2-1.dll` (or any other queried DLL) does not exist in current folder or in `$PATH`, so the condition fails and nothing is copied. Am I missing something?

This querying method works only for static libraries - at least for me.

**Comment by nolange** [comment]
No, it displays the **full path** to the library, but it has to exist in the compilers library search paths obviously. Are there some specific flags that are missing maybe, probably better to call with the used CFLAGS/LDFLAGS like
`${triplet}-gcc ${BASE_CPPFLAGS-} ${CPPFLAGS-} ${BASE_LDFLAGS-} ${LDFLAGS-} -print-file-name=$dll`.

here is what I get:
```
%  x86_64-w64-mingw32-gcc -print-file-name=libgcc_s_seh-1.dll
/usr/lib/gcc/x86_64-w64-mingw32/10-win32/libgcc_s_seh-1.dll
```

**Comment by FreddieChopin** [comment]
I've updated my comment a bit, as I've noticed that this indeed prints paths to files like `libm.a`, which are in the lib search path, but on Arch Linux the .dlls are in the same folder as the compiler executables.

> Are there some specific flags that are missing maybe, probably better to call with the used CFLAGS/LDFLAGS like
${triplet}-gcc ${BASE_CPPFLAGS-} ${CPPFLAGS-} ${BASE_LDFLAGS-} ${LDFLAGS-} -print-file-name=$dll.

Same effect, the command just repeats the filename, without the path.

**Comment by nolange** [comment]
if the dlls are not in the searchpath, then how can you link against them? Seems like a bug/issue related to Arch. `-print-file-name` should give you the absolute path the linker uses.

as a workaround you could add `-L /usr/${triplet}/bin`, maybe only after gcc found no libraries without that flag?

**Comment by FreddieChopin** [comment]
Don't ask me how it works, I have no idea (; The fact is that on Arch all `*.dll` files are in toolchain's `bin`, not its `lib` (that's why the path was hardcoded). I guess that to satisfy us both I'll have to introduce a 2-phase search for the DLLs.

> as a workaround you could add -L /usr/${triplet}/bin, maybe only after gcc found no libraries without that flag?

Nope, changes nothing /;

**Comment by nolange** [comment]
hmm, `-L` doesnt seem to do anything, gcc seems to only search the built-in paths (a bug in my opinion).

Anyway, I use `-print-file-name` for a decade now to locate the correct libraries, for a multilib/multiarch toolchain this will give you the correct paths for every `-march=` flag (thats why I am surprised you cant add search paths).
Arch not working is the exception, maybe your mingw compiler is a shell wrapper-script setting up the paths?

**Comment by FreddieChopin** [comment]
> maybe your mingw compiler is a shell wrapper-script setting up the paths

It's a real executable - I suspected something strange in this area, so I already checked it earlier.

> hmm, -L doesnt seem to do anything, gcc seems to only search the built-in paths (a bug in my opinion).

Probably with `-print-file-name` the `-L` flag is ignored. (a while of googling gives -> https://gcc.gnu.org/bugzilla/show_bug.cgi?id=87758 , but I suppose you already found it yourself (; )

**Pull request merged**
