### PR TITLE
fixes etc

### PR DESCRIPTION
**Pull request by Trass3r**
Just looking for some feedback. Feel free to comment.

### CODE REVIEW

**Review by FreddieChopin — COMMENTED** [review]
> use gcc-ar and friends
> use gcc-ar and friends for target

What does this achieve? I guess the change for target would allow to use LTO (maybe), but for host?

> use reasonable -march

Why? In all cases proper host tripled is passed via `--build=... --host=...`, so why force `haswell`?

> use -O3

Did you notice any significant difference with this option?

> use a reduced multilib profile

I assume this is your internal change to make test-builds faster.

> enable internal gcc assertions

Does it affect performnace of target compiler?

> there are some tools that run on the build machine 

Any explanation for that? (;

> all other

OK.

**Comment by FreddieChopin** [comment]
Sorry for clicking wrong buttons or clicking them too early, I updated my "review" with comments for each change.

**Comment by Trass3r** [comment]
> > use gcc-ar and friends
> > use gcc-ar and friends for target
> 
> What does this achieve? I guess the change for target would allow to use LTO (maybe), but for host?

Yep paves the way for LTO.

> Why? In all cases proper host tripled is passed via `--build=... --host=...`, so why force `haswell`?

How does the triple affect march, can't find any info. By default march is still a generic SSE2 machine if I'm not mistaken which is ridiculously old.

> > use -O3
> 
> Did you notice any significant difference with this option?

Haven't measured yet.

> > use a reduced multilib profile
> 
> I assume this is your internal change to make test-builds faster.

Yes, armv8 inflates the build time significantly (and I've yet to see an armv8-m mcu in practice).

> > enable internal gcc assertions
> 
> Does it affect performnace of target compiler?

Haven't measured. More of an internal change.

> > there are some tools that run on the build machine
> 
> Any explanation for that? (;

Can't remember 😄, maybe related to LTO.

**Comment by FreddieChopin** [comment]
I still don't know whether I should treat this as a genuine pull-request or as a private fork or as something entirely different...

**Comment by Trass3r** [comment]
Ah didn't know this was still tracking master. By now it has evolved into a fully automated trunk build.
Feel free to pick parts of it.

**Pull request closed without merging**
